/**
 * Envio HyperIndex scaffold generator.
 *
 * Envio (https://envio.dev) is a hosted (and self-hostable) EVM
 * indexer with a GraphQL API. Scaffold shape:
 *
 *   config.yaml          - chain + contract + events + handler path
 *   schema.graphql       - one entity type per event
 *   src/EventHandlers.ts - `<Contract>.<Event>.handler(async ...)`
 *   abis/<Contract>.json - the raw ABI
 *
 * The event-handler registration form uses the Envio-generated
 * `<Contract>.<Event>.handler` API (not the legacy
 * `<Contract>Contract.<Event>.handler` — that pattern was dropped in
 * the v2 runtime). Every event produces an entity named after it plus
 * a `loaderHandler` that populates the entity row with the event's
 * params, block metadata, and transaction hash.
 */

import {
  chainIdForNetwork,
  extractEvents,
  eventSignature,
  isTupleType,
  paramFieldName,
  parseArrayType,
  type AbiEvent,
  type AbiParameter,
} from "./indexer-shared.js";

export interface EnvioScaffoldOptions {
  contractName: string;
  network?: string;
  address?: string;
  startBlock?: number;
}

export interface EnvioScaffoldResult {
  files: Record<string, string>;
  events: string[];
  eventsWithTupleWarnings: string[];
}

export function generateEnvioScaffold(
  options: EnvioScaffoldOptions,
  abi: unknown[],
): EnvioScaffoldResult {
  const events = extractEvents(abi);
  const eventsWithTupleWarnings = events
    .filter((e) => e.inputs.some((p) => isTupleType(p.type)))
    .map((e) => e.name);

  const files: Record<string, string> = {
    "config.yaml": generateConfig(options, events),
    "schema.graphql": generateSchema(events),
    "src/EventHandlers.ts": generateHandlers(options.contractName, events),
    "package.json": generatePackageJson(options.contractName),
    ".env.example": generateEnvExample(),
    "README.md": generateReadme(options.contractName),
  };

  return {
    files,
    events: events.map((e) => e.name),
    eventsWithTupleWarnings,
  };
}

// ── config.yaml ──────────────────────────────────────────────────────

function generateConfig(opts: EnvioScaffoldOptions, events: AbiEvent[]): string {
  const {
    contractName,
    network = "mainnet",
    address = "0x0000000000000000000000000000000000000000",
    startBlock = 0,
  } = opts;
  const chainId = chainIdForNetwork(network);

  // Envio uses unindexed canonical signatures in `config.yaml` — the
  // `indexed` keyword is inferred from the ABI itself at codegen time.
  const eventsYaml =
    events.length === 0
      ? "      # No events detected in ABI. Add entries manually."
      : events
          .map((e) => `      - event: "${eventSignature(e, { includeIndexed: false })}"`)
          .join("\n");

  return `name: ${kebabCase(contractName)}
description: ${contractName} indexer generated by Solidity Workbench.
ecosystem: evm
networks:
  - id: ${chainId}
    start_block: ${startBlock}
    contracts:
      - name: ${contractName}
        address:
          - "${address}"
contracts:
  - name: ${contractName}
    handler: src/EventHandlers.ts
    events:
${eventsYaml}
    abi_file_path: abis/${contractName}.json
`;
}

// ── schema.graphql ───────────────────────────────────────────────────

function generateSchema(events: AbiEvent[]): string {
  if (events.length === 0) {
    return `# No events found in the ABI. Add your entity types here.
type Stub {
  id: ID!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
}
`;
  }

  const entities = events.map((e) => {
    const fields: string[] = ["  id: ID!"];
    for (const [i, p] of e.inputs.entries()) {
      const fieldName = paramFieldName(p, i);
      const gql = solidityTypeToGraphql(p);
      fields.push(`  ${fieldName}: ${gql}`);
    }
    fields.push("  blockNumber: BigInt!");
    fields.push("  blockTimestamp: BigInt!");
    fields.push("  transactionHash: String!");
    return `type ${e.name} {\n${fields.join("\n")}\n}`;
  });
  return entities.join("\n\n") + "\n";
}

function solidityTypeToGraphql(p: AbiParameter): string {
  if (isTupleType(p.type)) return "String! # TODO: encode tuple per your domain";
  const arr = parseArrayType(p.type);
  if (arr) {
    const elemGql = scalarGraphqlType(arr.element);
    return `[${elemGql.replace(/!$/, "")}!]!`;
  }
  return scalarGraphqlType(p.type);
}

function scalarGraphqlType(type: string): string {
  if (type === "address") return "String!";
  if (type === "bool") return "Boolean!";
  if (type === "string") return "String!";
  if (type === "bytes" || /^bytes\d+$/.test(type)) return "String!";
  if (/^u?int\d*$/.test(type)) return "BigInt!";
  return "String!";
}

// ── src/EventHandlers.ts ─────────────────────────────────────────────

function generateHandlers(contractName: string, events: AbiEvent[]): string {
  if (events.length === 0) {
    return `// No events detected in the ABI. Add Envio handlers here.
// Example:
//   import { ${contractName} } from "generated";
//   ${contractName}.SomeEvent.handler(async ({ event, context }) => { ... });
export {};
`;
  }

  const importedEntities = events.map((e) => e.name).join(",\n  ");

  const handlers = events
    .map((e) => {
      const assignments = e.inputs
        .map((p, i) => {
          const fieldName = paramFieldName(p, i);
          const paramAccess = p.name ?? fieldName;
          if (isTupleType(p.type)) {
            return `    ${fieldName}: JSON.stringify(event.params.${paramAccess}), // TODO: encode tuple`;
          }
          if (isBigIntFieldType(p.type)) {
            return `    ${fieldName}: event.params.${paramAccess},`;
          }
          // Envio's codegen renders `address` as string, `bytes` as
          // hex string, etc. — all valid GraphQL String inputs.
          return `    ${fieldName}: event.params.${paramAccess},`;
        })
        .join("\n");
      return `${contractName}.${e.name}.handler(async ({ event, context }) => {
  const entity: ${e.name} = {
    id: \`\${event.chainId}_\${event.block.number}_\${event.logIndex}\`,
${assignments}
    blockNumber: BigInt(event.block.number),
    blockTimestamp: BigInt(event.block.timestamp),
    transactionHash: event.transaction.hash,
  };
  context.${e.name}.set(entity);
});`;
    })
    .join("\n\n");

  return `import {
  ${contractName},
  ${importedEntities},
} from "generated";

${handlers}
`;
}

function isBigIntFieldType(type: string): boolean {
  return /^u?int\d*$/.test(type);
}

// ── package.json ─────────────────────────────────────────────────────

function generatePackageJson(contractName: string): string {
  const json = {
    name: `${kebabCase(contractName)}-envio`,
    private: true,
    type: "module",
    scripts: {
      codegen: "envio codegen",
      dev: "envio dev",
      start: "envio start",
      stop: "envio stop",
    },
    dependencies: {
      envio: "^2.0.0",
    },
    devDependencies: {
      "@types/node": "^20.0.0",
      typescript: "^5.3.0",
    },
  };
  return JSON.stringify(json, null, 2) + "\n";
}

// ── .env.example ─────────────────────────────────────────────────────

function generateEnvExample(): string {
  return `# Optional — set if you use Envio's managed RPC endpoints
# ENVIO_API_TOKEN=
`;
}

// ── README.md ────────────────────────────────────────────────────────

function generateReadme(contractName: string): string {
  return `# ${contractName} — Envio HyperIndex

Generated by Solidity Workbench.

## Quick start

\`\`\`bash
pnpm install
pnpm codegen   # regenerate TypeScript types from config.yaml + schema.graphql
pnpm dev       # local indexer + GraphQL playground on :8080
\`\`\`

Every event in the contract ABI has a matching entity in
\`schema.graphql\` and a handler in \`src/EventHandlers.ts\`. Tuple /
struct params are serialized via \`JSON.stringify\` into a String
column — replace those with domain-appropriate GraphQL shapes when
your indexing logic needs them.

See https://docs.envio.dev for the full HyperIndex reference.
`;
}

// ── helpers ──────────────────────────────────────────────────────────

function kebabCase(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}
